# Generated by Django 5.1.5 on 2025-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='business',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ChatbotSetting',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
