# Generated by Django 5.1.5 on 2025-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_business_user_remove_faq_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100, unique=True)),
                ('primary_background_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('secondary_background_color', models.CharField(default='#2d2d2d', max_length=7)),
                ('nav_background_color', models.CharField(default='#2d2d2d', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('accent_color', models.CharField(default='#7289da', max_length=7)),
                ('user_message_color', models.CharField(default='#4CAF50', max_length=7)),
                ('bot_message_color', models.CharField(default='#7289da', max_length=7)),
                ('bot_icon_background_color', models.CharField(default='#ff9800', max_length=7)),
                ('gradient_start_color', models.CharField(default='#7289da', max_length=7)),
                ('gradient_end_color', models.CharField(default='#a8b8ff', max_length=7)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('navbar_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('button_padding', models.CharField(default='12px 24px', max_length=50)),
                ('button_border_radius', models.CharField(default='10px', max_length=50)),
                ('button_font_size', models.CharField(default='16px', max_length=50)),
                ('message_animation_duration', models.FloatField(default=0.3)),
                ('message_icon_size', models.IntegerField(default=35)),
                ('suggestion_button_padding', models.CharField(default='10px 20px', max_length=50)),
                ('suggestion_button_border_radius', models.CharField(default='50px', max_length=50)),
            ],
        ),
    ]
