# Generated by Django 5.1.5 on 2025-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_faq_parent_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='response_time',
            field=models.FloatField(default=0),
        ),
    ]
