# Generated by Django 5.1.5 on 2025-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_querylog_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
