# Generated by Django 5.1.5 on 2025-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_querylog_is_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
